/**
 * Every client-facing string lives here. Components must never contain
 * hardcoded Dutch copy — import from `nl` instead.
 */
export const nl = {
  brand: {
    name: 'Candelaria',
    product: 'Mainframe',
    tagline: 'Owned Operations Layer',
  },

  login: {
    eyebrow: 'Klantportaal',
    title: 'Welkom terug',
    subtitle: 'Log in om je operations-omgeving te openen.',
    email: 'E-mailadres',
    emailPlaceholder: 'naam@bedrijf.nl',
    password: 'Wachtwoord',
    passwordPlaceholder: '••••••••',
    submit: 'Inloggen',
    submitting: 'Bezig met inloggen…',
    forgot: 'Wachtwoord vergeten?',
    footer: 'Beveiligde omgeving van Candelaria Agency.',
    errorInvalid: 'E-mailadres of wachtwoord klopt niet.',
    errorGeneric: 'Inloggen is niet gelukt. Probeer het opnieuw.',
  },

  forgotPassword: {
    title: 'Wachtwoord vergeten',
    subtitle: 'Vul je e-mailadres in, dan sturen we een link om je wachtwoord te resetten.',
    submit: 'Verstuur resetlink',
    submitting: 'Bezig met versturen…',
    sent: 'Als dit e-mailadres bekend is, is er een link verstuurd om het wachtwoord te resetten.',
    backToLogin: 'Terug naar inloggen',
    errorGeneric: 'Er ging iets mis. Probeer het opnieuw.',
  },

  resetPassword: {
    title: 'Nieuw wachtwoord instellen',
    subtitle: 'Kies een nieuw wachtwoord voor je account.',
    newPassword: 'Nieuw wachtwoord',
    confirmPassword: 'Herhaal wachtwoord',
    submit: 'Wachtwoord instellen',
    submitting: 'Bezig met opslaan…',
    missingToken: 'Deze link is ongeldig. Vraag een nieuwe resetlink aan.',
    errorMismatch: 'De wachtwoorden komen niet overeen.',
    errorGeneric: 'Er ging iets mis. Probeer het opnieuw.',
  },

  nav: {
    dashboard: 'Dashboard',
    agents: 'AI Agents',
    leads: 'Leads',
    social: 'Social',
    ads: 'Advertenties',
    seo: 'Website & SEO',
    automations: 'Automatiseringen',
    library: 'Bibliotheek',
    requests: 'Verzoeken',
    settings: 'Instellingen',
    'website-leads': 'Website Leads',
    analytics: 'Analytics',
    prospecting: 'Prospectie',
  },

  topbar: {
    environment: 'Demo-omgeving',
    dateRange: 'Deze maand',
    account: 'Account',
    logout: 'Uitloggen',
    openMenu: 'Menu openen',
    closeMenu: 'Menu sluiten',
  },

  roles: {
    admin: 'Beheerder',
    client_manager: 'Manager',
    client_viewer: 'Alleen lezen',
  },

  dashboard: {
    title: 'Dashboard',
    subtitle: 'Overzicht van je operations.',
    cards: {
      hoursSaved: 'Uren bespaard',
      leads: 'Leads deze maand',
      pipelineValue: 'Pipelinewaarde',
      reach: 'Totaal bereik',
      sessions: 'Websitesessies',
    },
    changelog: 'Wat is er gebeurd',
  },

  /** One entry per module. Phases 2-6 replace these placeholder pages. */
  modules: {
    agents: {
      title: 'AI Agents',
      subtitle: 'Je digitale medewerkers en wat ze hebben gedaan.',
    },
    leads: {
      title: 'Leads',
      subtitle: 'Alle aanvragen en gesprekken op één plek.',
    },
    social: {
      title: 'Social',
      subtitle: 'Geplande posts en prestaties per kanaal.',
    },
    ads: {
      title: 'Advertenties',
      subtitle: 'Campagnes, budget en rendement.',
    },
    seo: {
      title: 'Website & SEO',
      subtitle: 'Vindbaarheid, verkeer en technische gezondheid.',
    },
    automations: {
      title: 'Automatiseringen',
      subtitle: 'Workflows die op de achtergrond draaien.',
    },
    library: {
      title: 'Bibliotheek',
      subtitle: 'Documenten, merkmateriaal en rapportages.',
    },
    requests: {
      title: 'Verzoeken',
      subtitle: 'Dien een wijziging of nieuwe opdracht in.',
    },
    settings: {
      title: 'Instellingen',
      subtitle: 'Organisatie, gebruikers en koppelingen.',
    },
    'website-leads': {
      title: 'Website Leads',
      subtitle: 'Aanvragen via candelaria-agency.nl, met hun bezoekersreis.',
    },
    analytics: {
      title: 'Analytics',
      subtitle: 'Bezoekers, herkomst en gedrag op de website — eigen data, geen derde partij.',
    },
    prospecting: {
      title: 'Prospectie',
      subtitle: 'MKB-leads vinden, auditen, scoren en benaderen — Candelaria\'s eigen acquisitie-agent.',
    },
  },

  agents: {
    tabs: {
      overview: 'Overzicht',
      conversations: 'Gesprekken',
      escalations: 'Escalaties',
    },
    status: {
      active: 'Actief',
      paused: 'Gepauzeerd',
      error: 'Storing',
    },
    type: {
      chat: 'Chat',
      voice: 'Telefoon',
      email: 'E-mail',
      internal: 'Intern',
    },
    card: {
      conversationsWeek: 'Gesprekken deze week',
      avgDuration: 'Gem. gespreksduur',
      resolutionRate: 'Opgelost zonder hulp',
      viewDetail: 'Bekijk details',
    },
    detail: {
      back: 'Terug naar agents',
      volume: 'Gespreksvolume',
      resolution: 'Afhandeling',
      topics: 'Meest gestelde onderwerpen',
      sentiment: 'Stemming',
      tokens: 'Tokenverbruik',
      tokenInput: 'Invoer',
      tokenOutput: 'Uitvoer',
      tokenTotal: 'Totaal',
      rangeDay: 'Per dag',
      rangeWeek: 'Per week',
      rangeMonth: 'Per maand',
      totalConversations: 'Totaal gesprekken',
      lastConversation: 'Laatste gesprek',
      never: 'Nog geen gesprekken',
    },
    outcome: {
      resolved: 'Opgelost',
      escalated: 'Geëscaleerd',
      abandoned: 'Afgebroken',
    },
    sentiment: {
      positive: 'Positief',
      neutral: 'Neutraal',
      negative: 'Negatief',
    },
    log: {
      title: 'Gesprekken',
      subtitle: 'Doorzoek alle gesprekken en lees het volledige transcript.',
      search: 'Zoek in onderwerp of transcript',
      filterAgent: 'Agent',
      filterOutcome: 'Uitkomst',
      filterTopic: 'Onderwerp',
      filterFrom: 'Vanaf',
      filterTo: 'Tot en met',
      filterAll: 'Alle',
      reset: 'Filters wissen',
      results: 'gesprekken gevonden',
      colDate: 'Datum',
      colAgent: 'Agent',
      colTopic: 'Onderwerp',
      colChannel: 'Kanaal',
      colOutcome: 'Uitkomst',
      colDuration: 'Duur',
      colRating: 'Beoordeling',
      open: 'Open transcript',
      prev: 'Vorige',
      next: 'Volgende',
      page: 'Pagina',
      of: 'van',
    },
    transcript: {
      title: 'Transcript',
      close: 'Sluiten',
      roleUser: 'Klant',
      roleAssistant: 'Agent',
      roleSystem: 'Systeem',
      ratingLabel: 'Was dit gesprek goed afgehandeld?',
      ratingUp: 'Goed afgehandeld',
      ratingDown: 'Niet goed afgehandeld',
      ratingSaved: 'Bedankt, je beoordeling is opgeslagen.',
      empty: 'Dit gesprek heeft geen transcript.',
    },
    escalations: {
      title: 'Escalaties',
      subtitle: 'Gesprekken die een mens nodig hebben.',
      statusOpen: 'Open',
      statusInProgress: 'In behandeling',
      statusDone: 'Afgehandeld',
      note: 'Notitie',
      notePlaceholder: 'Wat is er met deze escalatie gebeurd?',
      markInProgress: 'In behandeling nemen',
      markDone: 'Markeer als afgehandeld',
      reopen: 'Heropenen',
      resolvedAt: 'Afgehandeld op',
      viewConversation: 'Bekijk gesprek',
      noneOpen: 'Geen openstaande escalaties.',
    },
  },

  requests: {
    newTitle: 'Nieuw verzoek',
    newButton: 'Nieuw verzoek',
    fieldTitle: 'Onderwerp',
    fieldTitlePlaceholder: 'Waar gaat het over?',
    fieldDescription: 'Toelichting',
    fieldDescriptionPlaceholder:
      'Beschrijf zo concreet mogelijk wat er moet gebeuren.',
    fieldPriority: 'Prioriteit',
    submit: 'Verzoek indienen',
    submitting: 'Bezig met versturen…',
    submitted: 'Je verzoek is ontvangen. We nemen het zo snel mogelijk op.',
    priority: {
      laag: 'Laag',
      normaal: 'Normaal',
      hoog: 'Hoog',
      urgent: 'Urgent',
    },
    status: {
      nieuw: 'Nieuw',
      in_behandeling: 'In behandeling',
      afgerond: 'Afgerond',
      afgewezen: 'Afgewezen',
    },
    boardEmpty: 'Geen verzoeken',
    thread: {
      title: 'Reacties',
      placeholder: 'Schrijf een reactie…',
      send: 'Plaatsen',
      sending: 'Bezig…',
      empty: 'Nog geen reacties.',
    },
    detail: {
      back: 'Terug naar verzoeken',
      submittedBy: 'Ingediend door',
      submittedOn: 'Ingediend op',
      changeStatus: 'Status wijzigen',
    },
    errors: {
      titleRequired: 'Vul een onderwerp in.',
      descriptionRequired: 'Vul een toelichting in.',
      generic: 'Er ging iets mis. Probeer het opnieuw.',
    },
  },

  settings: {
    tokens: {
      title: 'Ingest-tokens',
      subtitle:
        'Voor koppelingen die gespreksdata naar dit portaal sturen (agent-runtimes, automatiseringen).',
      newButton: 'Genereer nieuwe token',
      generating: 'Bezig met genereren…',
      namePlaceholder: 'Naam voor deze token, bv. "Productie-agent"',
      revealTitle: 'Nieuwe token aangemaakt',
      revealWarning:
        'Deze token wordt maar één keer getoond. Kopieer en bewaar hem nu ergens veilig.',
      copy: 'Kopiëren',
      copied: 'Gekopieerd',
      done: 'Klaar',
      colName: 'Naam',
      colStatus: 'Status',
      colCreated: 'Aangemaakt',
      colLastUsed: 'Laatst gebruikt',
      neverUsed: 'Nog niet gebruikt',
      statusActive: 'Actief',
      statusRevoked: 'Ingetrokken',
      revoke: 'Intrekken',
      revokeConfirm: 'Weet je het zeker?',
      revoking: 'Bezig…',
      empty: 'Nog geen tokens aangemaakt.',
      errors: {
        nameRequired: 'Geef de token een naam.',
        generic: 'Er ging iets mis. Probeer het opnieuw.',
      },
    },
  },

  websiteLeads: {
    colDate: 'Datum',
    colName: 'Naam',
    colEmail: 'E-mail',
    colCompany: 'Bedrijf',
    colStatus: 'Status',
    colCountry: 'Land',
    colSource: 'Bron',
    filterStatus: 'Status',
    filterPeriod: 'Periode',
    filterAll: 'Alle',
    periodToday: 'Vandaag',
    period7d: '7 dagen',
    period30d: '30 dagen',
    periodAll: 'Alles',
    noCompany: '—',
    directSource: '(direct)',
    status: {
      new: 'Nieuw',
      contacted: 'Benaderd',
      booked: 'Ingepland',
      won: 'Gewonnen',
      lost: 'Verloren',
    },
    empty: 'Nog geen leads binnengekomen.',
    detail: {
      back: 'Terug naar Website Leads',
      submitted: 'Binnengekomen op',
      contact: 'Contactgegevens',
      phone: 'Telefoon',
      website: 'Website',
      message: 'Bericht',
      security: 'Beveiliging',
      ipAddress: 'IP-adres',
      location: 'Locatie',
      rawPayload: 'Volledige inzending',
      changeStatus: 'Status wijzigen',
      journey: {
        title: 'Bezoekersreis',
        subtitle: 'Paginabezoeken vóór deze inzending, op basis van hetzelfde bezoekers-ID.',
        empty: 'Geen gekoppelde paginabezoeken gevonden.',
      },
    },
  },

  analytics: {
    period: {
      today: 'Vandaag',
      d7: '7 dagen',
      d30: '30 dagen',
      all: 'Alles',
    },
    kpi: {
      pageviews: 'Paginaweergaven',
      visitors: 'Unieke bezoekers',
      sessions: 'Sessies',
      pagesPerSession: 'Gem. pagina\'s per sessie',
      bounceRate: 'Bounce rate',
      conversionRate: 'Conversieratio',
    },
    dailyVisitors: 'Bezoekers per dag',
    location: {
      title: 'Locatie',
      byCountry: 'Per land',
      byCity: 'Per stad',
      colCountry: 'Land',
      colCity: 'Stad',
      colCount: 'Bezoeken',
      colShare: 'Aandeel',
    },
    sources: {
      title: 'Bronnen',
      referrers: 'Verwijzende domeinen',
      utm: 'UTM-campagnes',
      colSource: 'Bron',
      colCount: 'Bezoeken',
    },
    tech: {
      title: 'Techniek',
      device: 'Apparaat',
      browser: 'Browser',
      os: 'Besturingssysteem',
    },
    topPages: {
      title: 'Top pagina\'s',
      colPath: 'Pagina',
      colViews: 'Weergaven',
      colVisitors: 'Unieke bezoekers',
    },
    live: {
      title: 'Live',
      subtitle: 'Bezoekers in de afgelopen 5 minuten',
    },
    export: {
      button: 'Exporteer CSV',
      pageviews: 'Paginaweergaven (CSV)',
      leads: 'Leads (CSV)',
    },
    empty: 'Nog geen data — integratiesnippet op de website plaatsen.',
    deviceType: {
      mobile: 'Mobiel',
      tablet: 'Tablet',
      desktop: 'Desktop',
    },
  },

  changelog: {
    title: 'Wat is er gebeurd',
    addTitle: 'Nieuwe update',
    week: 'Week',
    weekPlaceholder: 'Week 31',
    entry: 'Wat is er gebeurd?',
    entryPlaceholder: 'Beschrijf in één zin wat er is opgeleverd.',
    add: 'Toevoegen',
    adding: 'Bezig…',
    viewAll: 'Alles bekijken',
  },

  common: {
    empty: 'Nog geen data',
    emptyHint: 'Zodra er gegevens binnenkomen verschijnen ze hier.',
    comingSoon: 'Volgt in een latere fase',
    loading: 'Laden…',
    save: 'Opslaan',
    cancel: 'Annuleren',
    demoBadge: 'Demodata',
    noAccess: 'Je hebt geen toegang tot dit onderdeel.',
  },

  prospecting: {
    tabs: {
      console: 'Console',
      leads: 'Leads',
      outbound: 'Outbound',
      health: 'Health',
      settings: 'Instellingen',
    },
    console: {
      startTitle: 'Nieuwe run starten',
      city: 'Plaats',
      sectors: 'Sectoren (komma-gescheiden)',
      limit: 'Max. kandidaten',
      start: 'Run starten',
      starting: 'Bezig…',
      noActiveRun: 'Geen actieve run.',
      running: 'Loopt',
      queued: 'In wachtrij',
      cancel: 'Run annuleren',
      cancelling: 'Bezig met annuleren…',
      conflictError: 'Er loopt al een run. Wacht tot deze klaar is of annuleer hem eerst.',
      genericError: 'Er ging iets mis bij het starten van de run.',
      events: 'Live gebeurtenissen',
      noEvents: 'Nog geen gebeurtenissen.',
      recentRuns: 'Recente runs',
    },
    leads: {
      priority: 'Prioriteit',
      score: 'Score',
      company: 'Bedrijf',
      city: 'Plaats',
      sector: 'Sector',
      painPoint: 'Pijnpunt',
      channel: 'Kanaal',
      status: 'Status',
      lastSeen: 'Laatst gezien',
      empty: 'Nog geen leads — start een run in de Console.',
      noResults: 'Geen resultaten binnen dit filter.',
      clearFilters: 'Wis alles',
      onlyWithEmail: 'Alleen met e-mail',
      minScore: 'Min. score',
      allSectors: 'Alle sectoren',
      allPriorities: 'Alle prioriteiten',
      backToList: 'Terug naar leads',
      tabOverview: 'Overzicht',
      tabEvidence: 'Bewijs',
      tabOutreach: 'Outreach',
      forget: 'Recht op vergetelheid',
      forgetConfirm: 'Deze lead wordt permanent verwijderd en nooit meer herontdekt. Doorgaan?',
      forgetDone: 'Verwijderd.',
    },
    status: {
      new: 'Nieuw',
      contacted: 'Benaderd',
      qualified: 'Gekwalificeerd',
      packed: 'Pack klaar',
      replied: 'Reactie ontvangen',
      won: 'Gewonnen',
      lost: 'Verloren',
      suppressed: 'Onderdrukt',
    },
    outbound: {
      dryRunBanner: 'Proefmodus actief — er wordt niets verstuurd.',
      liveBanner: 'Live modus actief.',
      halt: 'Noodstop',
      haltActive: 'Noodstop actief',
      resume: 'Hervatten',
      mailboxes: 'Mailboxen',
      queue: 'Wachtrij',
      replies: 'Reacties',
      sendLog: 'Verzendlog',
      enroll: 'Inschrijven voor outreach',
      enrolling: 'Bezig…',
    },
    health: {
      checklistTitle: 'Go-live checklist',
      dnsTitle: 'DNS-status',
      thresholdsTitle: 'Verzendgezondheid',
      chartTitle: 'Verzendingen — laatste 30 dagen',
      refresh: 'Vernieuwen',
    },
    settings: {
      icpTitle: 'ICP',
      rubricTitle: 'Rubric-gewichten',
      retentionTitle: 'Retentie',
      retentionRun: 'Nu uitvoeren',
      retentionConfirm: 'Weet je het zeker? Dit verwijdert data permanent.',
      versionHistory: 'Versiegeschiedenis',
      restore: 'Herstel vorige versie',
      restoring: 'Bezig...',
      active: 'actief',
    },
  },
} as const
