import type { ScoredSignal } from "@/lib/leads-agent/scoring/types";
import type { OutreachDrafts } from "@/lib/leads-agent/ai/outreach-pack";
import { buildIdentityFooter } from "./identity-footer";
import { buildEvidenceSheetMarkdown } from "./evidence-sheet";

export interface AssembledPack {
  email1: string;
  email2: string;
  email3: string;
  dmDraft: string;
  callScript: string; // JSON-stringified {opener, qualifyingQuestions, objectionResponses, close}
  evidenceMd: string;
  missingConfig: string[];
  wordCountWarnings: string[];
}

function wordCount(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

/**
 * Combines the Phase 5 AI drafts (persuasive body only) with the
 * deterministic §4 rule 7 compliance footer and the evidence sheet. The
 * footer is appended here, never generated by the model — see Phase 5's
 * outreach-pack.ts for why.
 */
export function assembleOutreachPack(params: {
  companyName: string;
  sourceUrl: string;
  socialProfileUrl?: string;
  drafts: OutreachDrafts;
  signals: ScoredSignal[];
}): AssembledPack {
  const footer = buildIdentityFooter(params.sourceUrl);
  const wordCountWarnings: string[] = [];

  const checkLimit = (label: string, text: string, max: number) => {
    const count = wordCount(text);
    if (count > max) wordCountWarnings.push(`${label}: ${count} woorden (limiet ${max}).`);
  };
  checkLimit("email1", params.drafts.email1Body, 120);
  checkLimit("email2", params.drafts.email2Body, 60);
  checkLimit("email3", params.drafts.email3Body, 40);

  const email1 = `${params.drafts.email1Body}\n\n${footer.text}`;
  const email2 = `${params.drafts.email2Body}\n\n${footer.text}`;
  const email3 = `${params.drafts.email3Body}\n\n${footer.text}`;
  const dmDraft = params.socialProfileUrl ? `${params.drafts.dmBody}\n\nProfiel: ${params.socialProfileUrl}` : params.drafts.dmBody;

  return {
    email1,
    email2,
    email3,
    dmDraft,
    callScript: JSON.stringify(params.drafts.callScript),
    evidenceMd: buildEvidenceSheetMarkdown(params.companyName, params.signals),
    missingConfig: footer.missingConfig,
    wordCountWarnings,
  };
}

/**
 * Definition of Done #11: "Content validation breaks the build when
 * identity block, opt-out, source line or privacy link is missing from
 * any template." No test suite is wired for this area yet (see prior
 * phases' notes), so this runs as a runtime assertion at generation time
 * instead — a broken assembly fails loudly rather than silently shipping
 * non-compliant content.
 */
export function validatePackContent(pack: AssembledPack, sourceUrl: string): void {
  const errors: string[] = [];
  for (const [label, text] of [
    ["email1", pack.email1],
    ["email2", pack.email2],
    ["email3", pack.email3],
  ] as const) {
    if (!text.includes("Candelaria Agency")) errors.push(`${label} mist identiteitsblok.`);
    if (!text.toLowerCase().includes("afmelden")) errors.push(`${label} mist afmeldregel.`);
    if (!text.includes(sourceUrl)) errors.push(`${label} mist bronregel.`);
    if (!text.includes("Privacyverklaring")) errors.push(`${label} mist privacyverklaring-link.`);
  }
  if (errors.length > 0) {
    throw new Error(`Outreach pack validatie mislukt: ${errors.join(" ")}`);
  }
}
